### ISSUE TITLE
Buttons point to your zabbix? And the script gives unboundLocal Errors

### ISSUE THREAD

**Issue by ekakela** [prestonr83/zbx-hipchat#1]
There is a part in the code that uses zabbix-instance urls from accusoft. Could these be a variable that can be changed easily? : 
`("<b><a href='https://zabbix.accusoft.com/"
                          "tr_comments.php?triggerid={0}'>More Information</a>"
                          " | <a href='https://zabbix.accusoft.com/events.php?"
                          "filter_set=1&triggerid={0}&period=604800'>Events</a>"
                          " | <a href='https://zabbix.accusoft.com/zabbix.php?"
                          "action=acknowledge.edit&acknowledge_type=1&"
                          "eventids[]={1}&backurl=tr_status.php'>Acknowledge"
                          "</a> | <a href='{2}'>Trigger Link</a></b>").format(
                              self._triggerid(), self._eventid(), self._url())},`

I'm also getting this error while running the notification

`Traceback (most recent call last):
  File "hipchat-card.py", line 211, in <module>
    main()
  File "hipchat-card.py", line 207, in main
    ZBXALERT.sendmsg()
  File "hipchat-card.py", line 195, in sendmsg
    self._formatmessage(), 'card': self._card(), 'message_format':
  File "hipchat-card.py", line 142, in _card
    statloz, statimg = self._statassets()
  File "hipchat-card.py", line 111, in _statassets
    return (statlozenge, img)
UnboundLocalError: local variable 'statlozenge' referenced before assignment`

**Comment by ekakela** [comment]
When running your initial commit instead of the current version, it works

**Comment by prestonr83** [comment]
I committed some updated code. Now there is a param for the Zabbix URL. I also added a bash file as a wrapper since some people were having an issue running the python script directly from Zabbix.

Try that out see if it works for you. You will need to update your media type within Zabbix.
